name: Scheduler Test

on:
  push:
    branches:
      - main

  schedule:
    - cron: "7,22,37,52 * * * *"

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Scheduler Test
        run: |
          echo "Workflow triggered!"
          echo "Event: ${{ github.event_name }}"
          echo "UTC:"
          date -u
          echo "IST:"
          TZ=Asia/Kolkata date
          
